"""add slug & slug function to Article Model

Revision ID: 0b26a54a077c
Revises: 5fe38dd70e47
Create Date: 2023-01-09 14:40:14.532981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b26a54a077c'
down_revision = '5fe38dd70e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
