"""remove last_updated_on

Revision ID: 0dc7de32c095
Revises: 8e0f4ca509ff
Create Date: 2023-01-02 19:35:35.417757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc7de32c095'
down_revision = '8e0f4ca509ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('last_updated_on')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_updated_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_on', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
