"""remove id from like tables

Revision ID: 59200e2dccf4
Revises: 4f87c3bc8567
Create Date: 2023-01-03 07:36:50.183812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59200e2dccf4'
down_revision = '4f87c3bc8567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
