"""renamed about_author to bio

Revision ID: 5fe38dd70e47
Revises: 8abc490b282f
Create Date: 2023-01-04 17:17:17.653719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe38dd70e47'
down_revision = '8abc490b282f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.TEXT(), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
