"""added article_id to CommentLike and ondelete=CASCADE to FKeys

Revision ID: 8abc490b282f
Revises: 59200e2dccf4
Create Date: 2023-01-03 19:57:48.522425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abc490b282f'
down_revision = '59200e2dccf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_article_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_article_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_articles_author_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_articles_author_id_users'), 'users', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comment_likes_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_likes_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comment_likes_article_id_articles'), 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_comments_article_id_articles', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_comments_article_id_articles'), 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_article_id_articles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_article_id_articles', 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key('fk_comments_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_likes_article_id_articles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_likes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_likes_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('article_id')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_articles_author_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_articles_author_id_users', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_article_likes_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_article_likes_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
