"""create relationships

Revision ID: ca8853da6972
Revises: 53f7cdecf3b1
Create Date: 2023-01-01 10:39:26.362552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8853da6972'
down_revision = '53f7cdecf3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_article_likes_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_article_likes_article_id_articles'), 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_articles_author_id_users'), 'users', ['author_id'], ['id'])

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('comment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_comment_likes_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comment_likes_comment_id_comments'), 'comments', ['comment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_article_id_articles'), 'articles', ['article_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_article_id_articles'), type_='foreignkey')
        batch_op.drop_column('article_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comment_likes_comment_id_comments'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comment_likes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('comment_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_articles_author_id_users'), type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('article_likes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_article_likes_article_id_articles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_article_likes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('article_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
